## 配置文件加载的优先级（由高到低）
##    bootstrap.properties -> bootstrap.yml -> application.properties -> application.yml

## 使用Spring Cloud时，Spring在还未初始化完成时会自动载入META-INF/spring.factories文件配置，
## 此时连接 Nacos 需要的配置只能通过在优先加载的配置文件中寻找，因此会选择 bootstrap.properties 文件作为Nacos的配置文件
## 旧版的 spring-cloud-starter-alibaba-nacos-config 模块包括了 spring-cloud-starter-bootstrap 依赖
## 必须使用使用 bootstrap.properties 来进行配置Nacos
## 但新版spring-cloud-starter-alibaba-nacos-config 模块剔除了 spring-cloud-starter-bootstrap 依赖
## Spring Cloud里并不主动加载 bootstrap.properties 文件了。但是必须要配置 spring.config.import: 支持导入多种途径的配置文件

spring:
  application:
    name: provider_config
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        # 默认指定的config配置文件类型为properties，现在更改为yaml或者yml。注意拼接的Nacos文件名要一致
        file-extension: yml
        # 同一个group中的不同服务可以共享以下 "共享配置"
        shared-configs[0]:
          data-id: shared_config.yml
          group: DEFAULT_GROUP
          refresh: true
        # 不同group中的不同服务可以共享以下 "扩展配置"
        extension-configs[0]:
          data-id: extension_config.yml
          group: DEFAULT_GROUP
          refresh: true
        extension-configs[1]:
          data-id: extension_config-two.yml
          group: DEFAULT_GROUP
          refresh: true
        ##### 加载顺序：共享配置 > 扩展配置([1]覆盖[0]) > 当前服务配置； 后加载的会将先加载的配置进行覆盖
  profiles:
    active: dev
  config:
    # 支持导入多种途径的配置文件
    import:
      # 导入Nacos注册中心的配置文件。原型对应上Nacos的配置文件名称，也就是Data Id。所以应该为：provider_config-dev.yml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}