spring:
  application:
    name: @project.artifactId@

customer:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql//localhost:3306/bottom_layer?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia
    username: root
    password: 131474
