# 应用服务 WEB 访问端口
server:
  port: 8080

# Elasticsearch搜索引擎
spring:
  application:
    name: Easy-Es
  data:
    elasticsearch:
      repositories:
        enabled: true     # 启用Spring Data Elasticsearch的存储库。
  elasticsearch:
    uris: localhost:9200  # Elasticsearch的连接URI为 “localhost:9200”
    connection-timeout: 5000 # 连接ElasticSearch超时时间

easy-es:
  enable: true   # 默认为true,若为false时,则认为不启用本框架
  address: 127.0.0.0:9200  # 填你的es连接地址
  banner: false  # 关闭启动时Easy-Es在控制台LOGO
  # username: 有设置才填写,非必须
  # password: 有设置才填写,非必须
