
server:
  port: 8080
  session:
    cookie:
      # 需要更换存放sessionId的cookie名字，否则认证服务和客户端的sessionId会相互覆盖
      name: JSESSIONID-2
logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  application:
    name: authorization-client
  security:
    oauth2:
      client:
        registration:
          client-id-1:
            provider: demo-client-id
            client-id: demo-client-id
            client-secret: demo-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            # client-authentication-method: POST
            scope: user_info, pull_requests
            client-name: demo-client-id
          client-id-2:
            provider: demo-client-id2
            client-id: demo-client-id
            client-secret: demo-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            # client-authentication-method: POST
            scope: user_info, pull_requests
            client-name: demo-client-id2
        provider:
          demo-client-id:
            authorization-uri: http://localhost:9090/oauth2/authorize
            token-uri: http://localhost:8082/oauth2/token
            user-info-uri: http://localhost:8082/user/info
            # 获取用户 xxx 属性的值（无默认，不能为空）
            user-name-attribute: name
            issuer-uri: http://localhost:9090
          demo-client-id2:
            authorization-uri: http://127.0.0.1:8080/oauth2/authorize
            token-uri: http://127.0.0.1:8080/oauth2/token
            user-info-uri: http://127.0.0.1:8082/user/info
            user-name-attribute: name
            jwk-set-uri: http://127.0.0.1:8080/oauth2/jwks



