
spring.application.name=@project.artifactId@

# Elasticsearch 配置
spring.elasticsearch.username=elastic
spring.elasticsearch.password=Z*h-KkWj6FGdy2gYUQpC
spring.elasticsearch.uris=http://localhost:9200
