server:
  port: 8080
  servlet:
    context-path: /api


spring:
  application:
    name: @project.artifactId@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 131474

mybatis-plus:
  # 配置Mapper扫描路径
  mapper-locations: classpath:mapper/*.xml
  # 配置实体类类型别名扫描路径。xml文件可省略全限定名称写法，直接书写别名即可
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
