server:
  port: 8088
  servlet:
    context-path: /

spring:
  application:
    name: provider-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC
    username: root
    password: 131474

logging:
  level:
    com:
      example: debug

mybatis:
  type-aliases-package: com.example.pojo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
