





### qq的smtp服务器主机(smtp.qq.com)；网易的smtp服务器主机(smtp.163.com)
spring.mail.host=smtp.qq.com
### 登录服务器邮箱账号
spring.mail.username=195630075@qq.com
### 登录服务器邮箱授权码（不是邮箱密码，这个是我们开通SMTP、POP时得到的授权码）
spring.mail.password=sropvxcigzghcafj