<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.example</groupId>
        <artifactId>04.8_Spring-Security-OAuth2</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <groupId>com.example</groupId>
    <artifactId>04.8_4-Custom-SpringAuthorizationServer</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>${project.artifactId}</name>
    <description>${project.artifactId}</description>

    <properties>
        <java.version>26</java.version>
    </properties>

    <modules>
        <module>OAuth2-Authorization-Server</module>
        <module>Custom-Authorization-Server</module>
        <module>Custom-Client</module>
    </modules>
    <!-- 该配置表示这个项目本身不产生任何代码（不生成 Jar 或 War 包），它只生成一个 pom.xml 文件作为构件，专门用来管理其他项目。 -->
    <packaging>pom</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
