
server:
    port: 8082

spring:
    application:
        name: authorization-server
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://127.0.0.1:8080/oauth2/jwks