
server:
  port: 8095

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 131474
    druid:
      # 连接池配置
      #初始化连接池的连接数量大小，最小，最大
      initial-size: 10
      min-idle: 10
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  sql:
    init:
      schema-locations: classpath:org/springframework/batch/core/schema-mysql.sql
      #mode: always
      mode: never
  batch:
    job:
      enabled: false


logging:
  level:
    com.example: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    default-executor-type: batch


job:
  data:
    path: /Users/youshicheng/IDEA/java-layout-path/SpringCloud以及前沿技术/27_Spring-Batch-ComprehensiveCase
