server.port=8080
server.servlet.context-path=/

#\u8BBE\u7F6Ethymeleaf\u6A21\u677F\u5F15\u64CE\u7684\u7F13\u5B58\uFF0C\u8BBE\u7F6E\u4E3Afalse\u5173\u95ED\uFF0C\u9ED8\u8BA4\u4E3Atrue\u5F00\u542F
spring.thymeleaf.cache=false


#\u8BBE\u7F6Ethymeleaf\u6A21\u677F\u5F15\u64CE\u7684\u524D/\u540E\u7F00\uFF08\u975E\u5FC5\u5199\uFF09
spring.thymeleaf.prefix=classpath:/static/
spring.thymeleaf.suffix=.html
