


#\u670D\u52A1\u5668\u7AEF\u53E3\u53F7
server.port=8088
#\u670D\u52A1\u5668\u4E0A\u4E0B\u6587\u8DEF\u5F84
server.servlet.context-path=/

#\u65E5\u5FD7\u7EA7\u522B
logging.level.com.cn.youshicheng=debug

#springjdbc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springdb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=131474

#mybatis\u5B9E\u4F53\u7C7B
mybatis.type-aliases-package=com.cn.youshicheng.pojo
