

# 设置端口号
server:
  port: 8080

# 设置日志级别
logging:
  level:
    com:
      youshicheng: debug

# 设置Eureka
spring:
  application:
    name: consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/

# 设置ribbon
ribbon:
  ConnectTimeout: 3000 # 请求连接的超时时间
  ReadTimeout: 3000    # 请求处理的超时时间

# 设置hystrix的超时时长
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

# 开启熔断降级
feign:
  hystrix:
    enabled: true


