
rocketmq:
  producer:
    isOnOff: on
    groupName: points_group
    namesrvAddr: 127.0.0.1:9876
    maxMessageSize: 4096
    sendMsgTimeout: 3000
    retryTimesWhenSendFailed: 2
  consumer:
    isOnOff: on
    groupName: points_group
    namesrvAddr: 127.0.0.1:9876
    topics: points~*
    consumeThreadMin: 20
    consumeThreadMax: 64
    consumeMessageBatchMaxSize: 1