
server:
    port: 8081
spring:
    application:
        name: nacos-provider
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springdb?serverTimezone=UTC
        password: 131474
        username: root
    cloud:
        nacos:
            discovery:
                # nacos服务地址
                server-addr: 127.0.0.1:8848
                # nacos登陆用户名
                username: nacos
                # nacos登陆密码
                password: nacos

logging:
    level:
        com:
            example: debug

management:
    endpoints:
        web:
            exposure:
                include: '*'
