spring:
  application:
    name: @project.artifactId@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/technician?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 131474

rocketmq:
  # NameServer 地址，集群使用';'隔开
  name-server: localhost:9876
  producer:
    # 生产者组名称【注意：消费分组不必与生产分组保持一致】
    group: Tx_Charge_Group

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
