# 应用名称
spring.application.name=@project.artifactId@
# 应用服务 WEB 访问端口
server.port=8083

# THYMELEAF (ThymeleafAutoConfiguration)
# 开启模板缓存（默认值： true ）
spring.thymeleaf.cache=false
# 检查模板是否存在，然后再呈现
spring.thymeleaf.check-template=true
# 检查模板位置是否正确（默认值 :true ）
spring.thymeleaf.check-template-location=true
# Content-Type 的值（默认值： text/html ）
spring.thymeleaf.servlet.content-type=text/html
# 开启 MVC Thymeleaf 视图解析（默认值： true ）
spring.thymeleaf.enabled=true
# 模板编码
spring.thymeleaf.encoding=UTF-8
# 要被排除在解析之外的视图名称列表，⽤逗号分隔
spring.thymeleaf.excluded-view-names=
# Thymeleaf 3.x 及以后：模板模式进行了重构和统一，不再单独区分 HTML5，而是合并为 HTML 模式（完全支持 HTML5 语法，且更先进）。
spring.thymeleaf.mode=HTML
# 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
spring.thymeleaf.prefix=classpath:/templates/
# 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
spring.thymeleaf.suffix=.html

# 设置连接数据库信息
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/technician?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=131474

# 指定MyBatis映射文件的路径
mybatis.mapper-locations=classpath:mapper/*.xml
