
spring.application.name=@project.artifactId@

# 配置视图解析器
# 1、不同于 JAR包 项目将 META-INF/resources/ 作为根路径。在 WAR包 项目下，是 webapp 目录被直接映射为根路径 /。
# 2、放在 resources 目录下的静态文件，用户可以通过 http://ip:port/xxx 直接访问。
# 3、而 WEB-INF 目录下的资源，用户无法通过 http://ip:port/WEB-INF/xxx.jsp 直接访问，只能通过服务器内部转发，符合 Jsp 的安全设计初衷。
# 因此在 WAR包 项目中，Jsp 文件会放在 webapp/WEB-INF 目录下。
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp
