mybatis:
    mapper-locations: classpath:mapper/*.xml
spring:
    application:
        name: SpringBoot3.x-ShardingSphere5
    datasource:
        driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
        url: jdbc:shardingsphere:classpath:sharding-config.yaml
