
server:
    port: 8080
    servlet:
        context-path: /
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 131474
        url: jdbc:mysql://localhost:3306/springdb?serverTimezone=UTC
        username: root
mybatis:
    type-aliases-package: com.example.domain