server:
  port: 8080
spring:
  sql:
    init:
      schema-locations: classpath:/static/yun6.sql
      mode: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.128:3306/dockerDatabase?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 131474
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      example: debug
