server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 注意：这里连接的 mysql 域名需要手动更新
    url: jdbc:mysql://192.168.215.2:3306/smc_ece?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/user.sql

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      example: debug
