DROP TABLE IF EXISTS `brand`;
CREATE TABLE `brand`(
    `Id`     bigint       NOT NULL AUTO_INCREMENT COMMENT '品牌id',
    `name`   varchar(255) DEFAULT NULL COMMENT '品牌名称',
    `image`  varchar(255) DEFAULT NULL COMMENT '品牌图片地址',
    `letter` varchar(255) DEFAULT NULL COMMENT '品牌的首字母',
    PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='品牌表';
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (1115, 'HTC', 'https://cdn.worldvectorlogo.com/logos/htc.svg', 'H');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (1528, 'LG', 'https://cdn.worldvectorlogo.com/logos/lg-1.svg', 'L');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (1912, 'NEC', 'https://cdn.worldvectorlogo.com/logos/nec-5.svg', 'N');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (2032, 'OPPO', 'http://img10.360buyimg.com/popshop/jfs/t2119/133/2264148064/4303/b8ab3755/56b2f385N8e4eb051.jpg', 'O');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (2505, 'TCL', 'https://cdn.worldvectorlogo.com/logos/tcl-3.svg', 'T');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (3177, '爱贝多', 'https://cdn.worldvectorlogo.com/logos/estrategia-negocio.svg', 'A');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (3539, '安桥（ONKYO）', 'https://cdn.worldvectorlogo.com/logos/onkyo.svg', 'A');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (3941, '白金（PLATINUM）', 'https://cdn.worldvectorlogo.com/logos/platinum.svg', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (4986, '波导（BiRD）', 'https://cdn.worldvectorlogo.com/logos/bird.svg', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (6522, '朵唯（DOOV）', 'https://cdn.worldvectorlogo.com/logos/dook.svg', 'D');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (6742, '飞利浦（PHILIPS）', 'http://img12.360buyimg.com/popshop/jfs/t18361/122/1318410299/1870/36fe70c9/5ac43a4dNa44a0ce0.jpg', 'F');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (7174, '富可视（InFocus）', 'https://cdn.worldvectorlogo.com/logos/infocus.svg', 'F');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (7203, '富士通（Fujitsu）', 'https://cdn.worldvectorlogo.com/logos/fujitsu.svg', 'F');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (7420, '格力（GREE）', 'https://cdn.worldvectorlogo.com/logos/gree.svg', 'G');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (7817, '海尔（Haier）', 'http://image.leyou.com/group1/M00/00/00/wKg4ZVrYZcyAVOzoAAB846UcmLg013.png', 'H');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (7888, '海信（Hisense）', 'https://cdn.worldvectorlogo.com/logos/hisense-logo.svg', 'H');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (8214, '黑莓（BlackBerry）', 'https://cdn.worldvectorlogo.com/logos/blackberry.svg', 'H');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (8551, '华硕（ASUS）', 'https://cdn.worldvectorlogo.com/logos/asus-logo.svg', 'H');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (8557, '华为（HUAWEI）', 'http://img10.360buyimg.com/popshop/jfs/t5662/36/8888655583/7806/1c629c01/598033b4Nd6055897.jpg', 'H');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (8740, '惠普（HP）', 'https://cdn.worldvectorlogo.com/logos/hp-2.svg', 'H');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (9420, '金立（Gionee）', 'https://cdn.worldvectorlogo.com/logos/pioneer.svg', 'J');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (9637, '京瓷（KYOCERA）', 'https://cdn.worldvectorlogo.com/logos/kyocera.svg', 'J');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (10317, '康佳（KONKA）', 'https://cdn.worldvectorlogo.com/logos/tonka-2.svg', 'K');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (10640, '酷派（Coolpad）', 'http://img10.360buyimg.com/popshop/jfs/t2521/347/883897149/3732/91c917ec/5670cf96Ncffa2ae6.jpg', 'K');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (11516, '联想（Lenovo）', 'http://img11.360buyimg.com/popshop/jfs/t6799/74/1348425607/15774/bc286188/59804c98N1944175e.jpg', 'L');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (12286, '漫步者（EDIFIER）', 'https://cdn.worldvectorlogo.com/logos/edifice-1.svg', 'M');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (12669, '魅族（MEIZU）', 'http://img13.360buyimg.com/popshop/jfs/t3511/131/31887105/4943/48f83fa9/57fdf4b8N6e95624d.jpg', 'M');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (13066, '摩托罗拉（Motorola）', 'https://cdn.worldvectorlogo.com/logos/motorola-new-logo.svg', 'M');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (13539, '诺基亚（NOKIA）', 'http://img11.360buyimg.com/popshop/jfs/t2572/102/189476501/7717/16cc5814/563b33d4N6c59780c.jpg', 'N');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (14026, 'Apple', 'http://img12.360buyimg.com/popshop/jfs/t2989/240/151377693/3895/30ad9044/574d36dbN262ef26d.jpg', 'A');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (14478, '青橙（GreenOrange）', 'https://cdn.worldvectorlogo.com/logos/-e-gameic.svg', 'Q');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (15127, '三星（SAMSUNG）', 'http://img14.360buyimg.com/popshop/jfs/t2701/34/484677369/7439/ee13e8fa/5716e2c4Nc925baf3.jpg', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (15539, '神舟（HASEE）', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (16506, '索爱（soaiy）', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (16538, '索尼（SONY）', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (16975, '天语（K-Touch）', '', 'T');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (17193, '外星人（Alienware）', '', 'W');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (17424, '威图', '', 'W');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (17440, '微软（Microsoft）', '', 'W');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (18078, 'NAMO', '', 'N');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (18362, '小辣椒', 'http://img14.360buyimg.com/popshop/g14/M00/09/10/rBEhV1K6uOwIAAAAAAAGxx0kTvQAAHWYwPIloIAAAbf434.png', 'X');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (18374, '小米（MI）', 'http://img10.360buyimg.com/popshop/jfs/t7084/169/439244907/4647/724c7958/598042c9N6e4e79e5.jpg', 'X');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (20130, '优思（Uniscope）', '', 'Y');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (20710, '长虹（CHANGHONG）', '', 'C');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (21011, '中兴（ZTE）', 'http://img13.360buyimg.com/popshop/jfs/t2551/271/1317227522/3284/7419745e/56a855a3Ne38ee719.jpg', 'Z');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (21360, 'beats', '', 'b');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (21553, '本易（BENEVE）', '', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (22261, 'tonino lamborghini', '', 'T');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (22575, '布鲁雅尔（Blueair）', '', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (23049, '广信（KINGSUN）', '', 'G');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (23130, '夏普（SHARP）', 'http://img12.360buyimg.com/popshop/jfs/t2458/315/2153417538/12751/2ff4e617/56b15fe9Naae1551d.jpg', 'X');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (25376, '马歇尔（Marshall）', '', 'M');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (25591, 'vivo', 'http://img13.360buyimg.com/popshop/jfs/t2458/318/1092287831/5774/b7b4ff89/563b3484N9ba68e13.jpg', 'V');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (27094, '努比亚（nubia）', 'http://img14.360buyimg.com/popshop/jfs/t2101/155/882410684/3730/b24b14db/5631cd12N7548352d.jpg', 'N');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (27306, '360', 'http://img10.360buyimg.com/popshop/jfs/t5182/149/2437584670/15334/2e1ebf3/591aa1abN602ebecf.jpg', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (32315, '其他', '', 'Q');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (36404, '金圣达（GRSED）', '', 'J');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (36652, '贝尔丰（BIFER）', '', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (36654, '大显（DaXian）', '', 'D');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (36657, '朗界（RugGear）', '', 'L');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (38125, 'SUGAR', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (38126, '美图（meitu）', 'http://img14.360buyimg.com/popshop/jfs/t3553/225/1930378991/5787/c2ebdd72/5836e479N88a98abb.jpg', 'M');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (38605, 'MANN', '', 'M');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (43644, '21KE', '', 'E');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (45227, '易百年', '', 'Y');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (45693, '威途（vertu）', '', 'V');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (45757, '欧奇（ouki）', '', 'o');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (49144, 'SPIGEN', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (50450, '亿和源（YHYON）', '', 'Y');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (51040, 'BIHEE', '', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (52302, '优购（UooGou）', '', 'Y');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (53317, '迪美（DIM）', '', 'D');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (54347, '尼凯恩（neken）', '', 'N');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (55524, 'B&O PLAY', '', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (56411, '誉品（YEPEN）', '', 'Y');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (59110, '诺亚信（NOAIN）', '', 'N');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (60106, '奥乐迪奥（AoleDior）', '', 'A');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (63032, '一加', 'http://img14.360buyimg.com/popshop/jfs/t2398/233/975959106/6263/a786f5b8/563b33ffN9c288c6c.jpg', 'Y');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (63833, '雷蛇（Razer）', '', 'L');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (68927, '詹姆士（GERMY）', '', 'G');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (89010, '纽曼（Newman）', '', 'N');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (91515, '锤子（smartisan）', 'http://img13.360buyimg.com/popshop/jfs/t1954/102/907711365/5487/9f26868f/5631ccdeNe8df5efb.jpg', 'C');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (102501, '赛博宇华（SOP）', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (104490, '谷歌（Google）', '', 'G');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (109150, '爱贝多（Babyfit）', '', 'A');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (110303, '万利达（Malata）', '', 'W');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (113718, '优它（YOTAPHONE）', '', 'Y');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (114119, 'TETC', '', 'T');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (123856, '炫华（xuanhua）', '', 'X');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (128080, '托尼洛·兰博基尼（Tonino Lamborghini）', '', 'T');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (129098, '木糖醇（MuTuCu）', '', 'M');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (130455, '爱玛（EMMA）', '', 'A');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (131546, '硕尼姆（Sonim）', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (133747, 'CAT', '', 'C');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (134922, 'ZUK', '', 'Z');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (135967, 'sungee', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (149070, 'AGM', '', 'A');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (151370, 'SOYES', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (151844, 'KODAK', '', 'K');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (155608, '施耐德（schneider）', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (159313, 'MOQI', '', 'M');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (174275, 'Essentials', '', 'E');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (178969, 'SAMWEI', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (179105, '小霸王（SUBOR）', '', 'X');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (179528, 'VETAS', '', 'V');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (179624, '优学派', '', 'Y');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (180213, '纽曼（Newman）', '', 'N');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (194213, 'DEVIALET', '', 'D');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (196065, 'SHANGPREE', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (197126, 'IMOO', '', 'I');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (203084, 'FNNI', '', 'F');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (204089, '小格雷', '', 'X');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (205278, 'COTTEE', '', 'C');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (209178, 'YAAO', '', 'Y');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (214915, '纽曼', '', 'N');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (219484, 'CONQUEST', '', 'C');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (221149, '铂爵（BIOJUET）', '', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (222294, '荣耀', '', 'R');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (223023, '保千里（PROTRULY）', '', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (223199, 'Blu', '', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (223316, 'unruly', '', 'U');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (225085, 'Tonino Lamborghini', '', 'T');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (228280, '守护宝', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (233984, '8848', '', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (234746, 'Gold Elite', '', 'G');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (238798, 'HONOR', '', 'H');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (240112, 'BIXING', '', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (246053, '锐族', '', 'R');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (247149, '国美（GOME）', '', 'G');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (247652, '中兴健康（ZTE Health）', '', 'Z');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (248132, 'YOSTAR', '', 'Y');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (249404, '创星', '', 'C');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (253520, 'VERTU', '', 'V');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (261196, 'LBER', '', 'L');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (261480, '滝风（ION MEDIC）', '', 'L');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (262180, '梦幻门（MENG HUAN MEN）', '', 'M');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (262334, '意龍（E&L）', '', 'Y');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (264451, '艾尼卡（Anica）', '', 'A');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (265247, 'DMZ DAMUZHI', '', 'D');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (267981, 'UNNO', '', 'U');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (271696, '红鸟', '', 'H');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (276102, '紐萬（Niuwan）', '', 'N');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (276381, 'Podor', '', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (276780, '海语（HAIYU）', '', 'H');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (278268, 'YISON', '', 'Y');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (278755, 'SOAP', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (279173, 'renebelle', '', 'R');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (280120, 'AKESR', '', 'A');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (280152, 'YOTA', '', 'Y');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (284571, 'HOOLFINE', '', 'H');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (285331, '金柏利', '', 'J');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (286273, 'BLACKPOULO', '', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (287292, 'SIMPLEWAY', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (290104, 'KaiDC', '', 'K');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (290682, '奥缇斯（autrise）', '', 'A');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (302250, '橄榄树（Olive tree）', '', 'G');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (304654, 'HIGE', '', 'H');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (314866, '360手机', '', 'S');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (316578, '克里特（kreta）', '', 'k');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (316596, 'HOOLFINE', '', 'H');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (316618, 'RONXS', '', 'R');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (325396, '飞利浦（PHILIPS）', '', 'P');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (325398, '比亚兹（ESK）', '', 'B');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (325399, '亿色(ESR)', '', 'Y');
INSERT INTO `brand` (`id`, `name`, `image`, `letter`) VALUES (325401, '黑马', 'http://image.leyou.com/group1/M00/00/00/wKg4ZVro8haAdtRLAALAv4YTyno368.png', 'H');
