

server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.8.112:9300
      #cluster-nodes集群节点,相当于注册的端口9300的es服务
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl