# 启动端口设置
server:
  port: 8080
  servlet:
    context-path: /

# 配置日志，可方便mybatis查询数据的信息日志
logging:
  level:
    com:
      example:
        mapper: debug

# jdbc配置
spring:
  application:
    name: ${project.artifactId}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb?serverTimezone=UTC
    username: root
    password: 131474
  data: # Elasticsearch配置
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: localhost:9200
      connection-timeout: 5000
  devtools: # java热部署
    restart:
      enabled: true
      additional-paths: src/test/java     # 热部署路径
