<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.example</groupId>
    <artifactId>SpringBoot_EntitySerialization</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>SpringBoot_实体类序列化</name>
    <description>SpringBoot_实体类序列化</description>

    <properties>
        <java.version>26</java.version>
    </properties>

    <dependencies>
        <!-- SpringBoot 3 Web依赖 中会传递依赖 Jackson2，但是在 SpringBoot 4 Web依赖 中传递的是 Jackson3
             Jackson2 与 Jackson3 区别：
                1、将所有代码中 com.fasterxml.jackson 的导入语句，替换为 tools.jackson。（排除 @JsonProperty等注解类型）
                2、将 ObjectMapper 的实例化方式改为使用 JsonMapper.builder()
                3、JsonSerializer<T>、JsonDeserializer<T> 被重命名为 ValueSerializer<T>、ValueDeserializer<T>
                4、一个重要的例外是 jackson-annotations 模块中的注解（如 @JsonProperty），它们为了保持兼容性，仍然保留在 com.fasterxml.jackson.annotation 包下。
         -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- jackson版本2 -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.21.5</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>2.0.46.android8</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
