
# ShardingSphere 配置文件
dataSources:
  master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: 131474
  slave1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb
    username: root
    password: 131474
  slave2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/caoyumin
    username: root
    password: 131474

rules:
    dataSources:
      # 读写分离逻辑数据源名称
      readwrite_ds:
        # 读写分离类型:静态策略(staticStrategy)、动态策略(dynamicStrategy)
        staticStrategy:
          # 写库数据源名称
          writeDataSourceName: master
          # 读库数据源名称，多个从数据源用逗号分隔，或者使用数组表示
          readDataSourceNames:
            - slave1
            - slave2
        # 负载均衡算法名称
        loadBalancerName: round_robin
    # 负载均衡算法配置
    loadBalancers:
      # 负载均衡算法名称
      round_robin:
        # 负载均衡算法类型
        type: ROUND_ROBIN
        # 负载均衡算法属性配置
        # props:
        # ...

