# 配置端口
server:
  port: 8085
  servlet:
    # context-path: /api
    application-display-name: @project.artifactId@

spring:
  application:
    name: @project.artifactId@

  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/technician?serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true # MySQL在高版本需要指明是否进行SSL连接 解决则加上 &useSSL=false
    name: mysql
    username: root
    password: 131474
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

# SpringSecurity 禁用 Actuator 端点的安全控制
management:
  endpoints:
    web:
      exposure:
        include: health,info  # 仅暴露健康检查和基本信息
  endpoint:
    health:
      show-details: always

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  # mapper-locations: classpath:**/*Mapper.xml
  # 指定 MyBatis 配置文件的位置。
  # config-location: classpath:mybatis-config.xml
  global-config: # 全局配置
    banner: true # 是否打印 Mybatis-Plus 的 banner
    db-config:
      # 主键类型  AUTO:"数据库ID自增"  INPUT:"用户输入ID"  ID_WORKER:"全局唯一ID (数字类型唯一ID)"  UUID:"全局唯一ID UUID";
      id-type: auto
      table-prefix: sys_   # 表前缀
      # 驼峰下划线转换
      table-underline: true
      # 自定义表主键生成器
      # key-generators: com.example.CustomKeyGenerator
      # 全局的 Entity 逻辑删除字段属性名，仅在逻辑删除功能打开时有效。
      logic-delete-field: delFlag
      # 逻辑删除配置
      logic-delete-value: 1     # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      # insert-strategy: NEVER
      # update-strategy: ignored
      # where-strategy: ALWAYS
  configuration:
    # 是否开启自动驼峰命名规则映射：从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # cache-enabled: false
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    # call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 解决oracle更新数据为null时无法转换报错，mysql不会出现此情况
    # jdbc-type-for-null: 'null'

logging:
  level:
    com:
      example: debug

# 自定义的安全认证
security:
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10
  ignoreUrls:
    - /toLogin
    - /dashboard
    - /system/settings
    - /data/management
    - /order/management
    - /product/management
    - /customer/management
    - /finance/management
    - /reports/analytics
    - /index
    - /logout
    - /*/*.js
    - /*/*.css
    - /*/*.png
    - /*/*.ico
