
spring.application.name=@project.artifactId@

# 配置端口号
server.port=9090
server.servlet.context-path=/

# 配置视图解析器
# 1、在 JAR包 项目下，Servlet 3.0 规范规定，META-INF/resources/ 目录会被映射为根路径 /。
# 2、放在 resources 目录下的静态文件，用户可以通过 http://ip:port/xxx 直接访问。
# 3、而 WEB-INF 目录下的资源，用户无法通过 http://ip:port/WEB-INF/xxx.jsp 直接访问，只能通过服务器内部转发，符合 Jsp 的安全设计初衷。
# 因此在 JAR包 项目中，Jsp 文件会放在 META-INF/resources/WEB-INF 目录下。
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp
