server:
  port: 9090

logging:
  level:
    org:
      springframework:
        security: debug

spring:
  application:
    name: demo-server
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_oauth2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 131474
  sql:
    init:
      # always: 表示总是执行 schemaLocations 和 dataLocations 声明的脚本
      # embedded: 表示只有是内存数据库（如 H2, HSQLDB）时，会在每次启动时删除并重新创建数据库。
      # never: 表示不执行
      mode: never
      schema-locations:
        - classpath:org/springframework/security/oauth2/server/authorization/client/oauth2-registered-client-schema.sql
        - classpath:org/springframework/security/oauth2/server/authorization/oauth2-authorization-consent-schema.sql
        - classpath:org/springframework/security/oauth2/server/authorization/oauth2-authorization-schema.sql
  security:
    # 用户注册
    user:
      name: admin
      password: 123
