

#设置端口号
server.port=8088
#设置上下文根
server.servlet.context-path=/

#设置日志级别
logging.level.com.youshicheng=debug

#springjdbc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springdb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=131474


#mybatis指定连接实体类
mybatis.type-aliases-package=com.youshicheng.pojo

#注册中心的相关配置
spring.application.name=provice-service
eureka.client.service-url.defaultZone=http://127.0.0.1:10086/eureka/


#在注册服务完成后，服务提供者会维持一个心跳。我们称为服务的续约
#服务续约的间隔，默认为30秒。就是每隔30秒向注册中心发送一次心跳
eureka.instance.lease-renewal-interval-in-seconds=30
#服务失效时间，默认值是90秒。超过90秒没有发送心跳，Eureka就会认为该服务宕机，会从服务列表中移除。
#一般来说，这两个值都是默认的，可以不写。
eureka.instance.lease-expiration-duration-in-seconds=90

#还有剔除失效和自我保护的概念，一般可能在面试时会被问到。有兴趣可以去了解。

