spring:
    application:
        name: @project.artifactId@

langchain4j:
    open-ai:
      chat-model:
        # 你的OpenAI API密钥（必填，从OpenAI官网获取）
        api-key: 0221ee205aba48b48196f38920f721fa.VFNjN9n8WKuUGGc1XFYAQRBL
        # 模型名称（可选，默认gpt-3.5-turbo，可指定gpt-4/gpt-4o）
        model-name: qwen3.5:4b
        # 超时时间（可选，默认10s，网络差可调大）
        timeout: 30s
