


#\u8BBE\u7F6E\u5185\u5D4CTomcat\u7AEF\u53E3\u53F7
server.port=8080
#\u8BBE\u7F6E\u4E0A\u4E0B\u6587\u6839
server.servlet.context-path=/

#\u8BBE\u7F6Edubbo\u7684\u914D\u7F6E
spring.application.name=12_springboot-dubbo-consumer
#\u8BBE\u7F6E\u6CE8\u518C\u4E2D\u5FC3
spring.dubbo.registry=zookeeper://localhost:2181