
server:
  port: 9299

spring:
  application:
    name: cloud-sentinel-feign
  cloud:
    sentinel:
      # 取消控制台懒加载
      eager:
        true
      transport:
        # 控制台地址
        dashboard: 127.0.0.1:8010
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

# 开启Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true
