

#\u8BBE\u7F6E\u5185\u5D4CTomcat\u7AEF\u53E3\u53F7
server.port=8081
#\u8BBE\u7F6E\u4E0A\u4E0B\u6587\u6839
server.servlet.context-path=/

#\u8BBE\u7F6E\u8FDE\u63A5\u6570\u636E\u5E93\u4FE1\u606F
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springdb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=131474

#\u8BBE\u7F6Edubbo\u7684\u914D\u7F6E
spring.application.name=14_springboot-dubbo-ssm-provider
#\u5F53\u524D\u5DE5\u7A0B\u662F\u4E00\u4E2A\u670D\u52A1\u63D0\u4F9B\u8005
spring.dubbo.server=true
#\u8BBE\u7F6E\u6CE8\u518C\u4E2D\u5FC3
spring.dubbo.registry=zookeeper://localhost:2181


#\u8BBE\u7F6Eredis\u914D\u7F6E\u4FE1\u606F
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.password=131474