# 启动导引配置
# 在Spring Boot启动时，第一个加载的配置文件，Application.yml 优先级———1
# 为Spring Boot初始化环境，提供一个预加载配置
# 当前配置Spring Cloud Config Server 位置，和要加载的相关配置参数
# 加载application.yml。 优先级———2
# 加载application-profiles.yml。 优先级———3

spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: config_application  # 要加载的配置文件名称
      label: master             # 要加载的配置，所在分支命名，默认为null，相当于master
      # profile: default        # 要加载的配置的profile是什么，默认default
      profile: dev              # 这里我使用的是版本是test。上述配置组装文件就是：config_application-dev.yml

# 这些热刷新配置信息可以写在远程仓库的配置中心，但也可以写在客户端
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - info
          - health
          - refresh  # 热刷新服务   只处理POST请求。实现Spring容器热刷新
