
server:
  port: 9090

logging:
  level:
    org:
      springframework:
        security: trace

spring:
  application:
    name: demo-server
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  security:
    # 用户注册
    user:
      name: admin
      password: 123
    oauth2:
      authorizationserver:
        client:
          # 客户端名称
          myClient:
            registration:
              # 客户端id
              client-id: ysc
              # 客户端密钥（｛noop｝这种格式的密钥只有授权服务器端需要配置）
              client-secret: '｛noop｝123456'
              # 客户端授权模式(client_secret_basic, client_secret_post、private_key_jwt, client_secret_jwt)
              client-authentication-methods:
                # 客户端的client_id和client_secret放在请求头中传递给授权服务器
                - client_secret_basic
              # 授权类型（授权码、刷新token）
              authorization-grant-types:
                - authorization_code
                - refresh_token
              # 客户端回调地址（谨慎使用127.0.0.1）
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/myClient
              # 客户端应用首页（谨慎使用127.0.0.1）
              post-logout-redirect-uris:
                - http://127.0.0.1:8080/
              # 授权范围
              scopes:
                # 用户的唯一标识符
                - openid
                # 用户的个人信息
                - profile
            # 是否需要"授权确认"
            require-authorization-consent: true