

server.port=8080
server.servlet.context-path=/


logging.level.com.example.springbootshirojwt=debug


#springjdbc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/yun6?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=131474

