server:
  port: 9800

spring:
  application:
    name: sentinel-jar
  cloud:
    sentinel:
      # 取消控制台懒加载，这样就可以在访问Sentinel控制台的时候，不需要通过访问资源，就能在控制台显示资源信息
      eager:
        true
      transport:
        # 启动一个与Dashboard通信的进程，默认端口为8719
        # 这里的 spring.cloud.sentinel.transport.port 端口配置会在应用对应的机器上启动一个 Http Server，
        # 该Server会与 Sentinel控制台做交互。比如 Sentinel控制台添加了一个限流规则，会把规则数据push给这个Http Server接收，
        # Http Server 再将规则注册到 Sentinel 中。
        # 理解以下两个端口：8010相当于Sentinel的前端服务；8719相当于Sentinel的后端服务
        port: 8719
        # 控制台仪表盘地址
        dashboard: 127.0.0.1:8010
