server:
  port: 8080
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: 127.0.0.1:8848
        # nacos登陆用户名
        username: nacos
        # nacos登陆密码
        password: nacos
        # 是否设置为临时实例：默认为true，表示当前服务注册到Nacos中为临时实例
        # ephemeral: false

logging:
  level:
    com:
      example: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
