
server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/technician?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 131474
  sql:
    init:
      # always: 表示总是执行 schemaLocations 和 dataLocations 声明的脚本
      # embedded: 表示只有是内存数据库（如 H2, HSQLDB）时，会在每次启动时删除并重新创建数据库。
      # never: 表示不执行
      mode: never
      # 表示执行DDL脚本 （这里的路径是spring-batch-core中依赖里的sql脚本，替换成自己的sql脚本也可以）
      schema-locations: classpath:org/springframework/batch/core/schema-mysql.sql # 或者 classpath:schema-mysql.sql
      # 表示执行DML脚本 （一些insert、update、delete语句脚本）
      data-locations:
