
spring:
  application:
    name: @project.artifactId@
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-config.yml

mybatis:
  mapper-locations: classpath:mapper/*.xml
