spring:
    application:
        name: Mybatis-BottomLayer2

customer:
    datasource:
        driver: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql//localhost:3306/springdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia
        username: root
        password: 131474