
server:
    port: 8082

spring:
    application:
        name: authorization-server
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:9090/oauth2/jwks